PAGE_URL = "https://cars.kg/offers/{}.html"


class CarTemp():
    URL = "URL"
    PRICE = "Цена"
    MILEAGE = "Пробег"
    POWER = "Мощность"
    CAPACITY = "Объём"
    YEAR = "Год выпуска"
    CARCASS = "Тип кузова"
    TRANSMISSION = "КПП"
    DRIVE = "Привод"
    WHEEL = "Руль"
    FUEL = "Топливо"
    BRAND = "Марка"
    COLOR = "Цвет"
    PUBLISHED_AT = "Дата рекламы"
    MODEL = "Модель"
    PHOTO_URLS = "Фото"
    EXPIRED = "Активность"
